---

env:
  browser: true
  node: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - "jest-enzyme"
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

rules:
  no-console: 0